#!/bin/bash

set -e

echo
echo "===> Build started at $(date)"
echo
START=$SECONDS

# Unconditionally print elapsed build time at exit
function finish {
  echo "===> Elapsed time: $(($SECONDS - $START)) seconds"
}
trap finish EXIT

echo "---> Preparing source..."
mkdir -p $SOURCE

cp -Rf /tmp/src/. $SOURCE

cd $SOURCE

echo "---> Downloading dependencies..."
go get -v ./...

echo "---> Building application source..."
# https://medium.com/@kelseyhightower/optimizing-docker-images-for-static-binaries-b5696e26eb07
CGO_ENABLED=0 GOOS=linux go build -v -a -tags netgo -ldflags '-w' -o main .
# CGO_ENABLED=0 go build -v -a -ldflags '-s' -installsuffix cgo -o main .
# go build -v -o main

# SKIP INSTALLING SINCE THIS IS JUST A STATIC GO BUILDER
# go install main

echo
echo "===> Build completed at $(date)"

# Fix source directory permissions
fix-permissions ./

echo "Binary at $SOURCE"
